### ISSUE TITLE
Some aliases get overridden by zsh

### ISSUE THREAD

**Issue by Frusty** [matthewmccullough/dotfiles#2]
I noticed that you have put in aliases for ls (and ll), which I also like.

But I noticed that when doing
```source $ZSH/oh-my-zsh.sh```
in the .zshrc, those will get overridden by zsh specific aliases in oh-my-zsh/lib/aliases.zsh.

Any idea how to bend it, so that my profile is loaded AFTER zsh has done it's part?

What have you done to go around this or are you just living with it?

Thanks, Jan

**Comment by matthewmccullough** [comment]
Due to time and attention being pulled to other projects, I have to be honest with myself that I'm not able to dig into this in the near future, though I'd love help if anyone has the time!
