### ISSUE TITLE
`TITLEBAR` variable in bash_gitprompt is not defined anywhere

### ISSUE THREAD

**Issue by sudar** [matthewmccullough/dotfiles#3]
The `TITLEBAR` variable in bash_gitprompt file is not defined anywhere and is first used at line 50
https://github.com/matthewmccullough/dotfiles/blob/master/bash_gitprompt#L50

**Comment by matthewmccullough** [comment]
Due to time and attention being pulled to other projects, I have to be honest with myself that I'm not able to dig into this in the near future, though I'd love help if anyone has the time!
