### ISSUE TITLE
git status output format changed

### ISSUE THREAD

**Issue by jorgev** [matthewmccullough/dotfiles#6]
The output from the "git status" command has changed slightly. Specifically, the '#' prefix has been removed. This causes the regular expressions to fail in the bash_gitprompt script. It appears this change was introduced in version 1.8.5.  Please see:

https://github.com/git/git/commit/2556b9962e7c0353d562b7bf70eed11d8f29d0b0

As you can see from the commit message, it looks like they've added a way to get the old behavior using the status.displayCommentPrefix setting. So, I guess you could leave your script as is.  I tried to find a clever way to modify the script so that it would work with older and newer versions, but it got a little messy since bash doesn't support non-capturing groups, preventing me from writing something like "^(?:# )? On branch...". I guess you could do something like "^#? ?On branch..." but it starts to get a little ugly. I'll leave it to someone with a lot more bash experience. Or, as I said, you could just close this issue and maybe add a comment for users to set status.displayCommentPrefix in their config file.

Cheers.

**Comment by matthewmccullough** [comment]
> add a comment for users to set status.displayCommentPrefix in their config file.

I'm woefully late in addressing this, but still very appreciative of the level of detail and research you've brought to this.  I'm going to go the "add a comment for users to set `status.displayCommentPrefix` in their config file." route.

**Comment by matthewmccullough** [comment]
> it starts to get a little ugly

Indeed. Checked out this path again. You're totally right, @jorgev. Going to have to stick with `status.displayCommentPrefix` as the solution for now.
